### ISSUE TITLE
gitstat.rb running failed on my macbook with ruby2.3.1

### ISSUE THREAD

**Issue by zwyin** [chenyukang/VisualizeGit#1]
at first, thank you for writing such a tool for code analysis purpose.
I have found this tool from you blog page: 
http://cyukang.com/2014/04/18/visualize-git-proj.html

what I have done
- clone this project into my local laptop
- copy two files out of project into my code folder. (gitstat.rb and gitshow.py)
- running command as below
./gitstat.rb -o log.txt
- then I found this error, as I am quite strage with ruby syntax, after reading for a while, i am trying to contact you for solution, thanks in advance.
```
{:output=>"log.txt"}

detect_gits
./gitstat.rb:76:in `run': undefined method `each' for nil:NilClass (NoMethodError)
	from ./gitstat.rb:108:in `<main>
```

**Comment by chenyukang** [comment]
Hi @zwyin ,
  Thanks for reporting an issue, I have reproduced it on my Mac, 
   I found the README is not correct, 
   the script usage is: 
```shell
     ./gitstat.rb -l project_dir1 project_dir2 -o log.txt
    # if you are in project dir, you should use as:
     ./gitstat.rb -l ./ -o log.txt
```
   This are just some toy scripts, I recommend you play with https://github.com/acaudwell/Gource,
   Which is production ready, 🤒
